# Generated by Django 5.1.7 on 2025-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
