# Generated by Django 5.2 on 2025-04-27 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceType', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('PSU', 'PSU'), ('MOBO', 'MOTHERBOARD'), ('CASE', 'CASE'), ('COOLER', 'COOLER'), ('FAN', 'FAN')], max_length=12)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('power', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listingID', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('deviceID', models.ForeignKey(default=14, on_delete=django.db.models.deletion.RESTRICT, to='RedTiger.device')),
                ('sellerID', models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.SmallAutoField(default=10, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('productID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='RedTiger.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedTiger.listing')),
            ],
            options={
                'unique_together': {('userID', 'listingID')},
            },
        ),
    ]
