# Generated by Django 5.1.7 on 2025-04-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
