# Generated by Django 5.1.7 on 2025-04-20 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deviceID',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.RESTRICT, to='RedTiger.device'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sellerID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='productID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='RedTiger.listing'),
        ),
    ]
