# Generated by Django 5.2 on 2025-04-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Like New', 'Like New'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Acceptable', 'Acceptable'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], default='Brand New', max_length=20),
        ),
    ]
