# Generated by Django 5.1.7 on 2025-04-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
