# Generated by Django 5.2 on 2025-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0002_device_image_url_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='storage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
