# Generated by Django 5.0 on 2025-04-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0002_alter_listing_deviceid_alter_listing_sellerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceID',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingID',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
