# Generated by Django 5.2 on 2025-04-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0003_alter_device_deviceid_alter_listing_listingid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('pk', models.CompositePrimaryKey('userID', 'listingID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedTiger.listing')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
