# Generated by Django 5.2 on 2025-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0003_alter_device_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
