# Generated by Django 5.1.7 on 2025-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.SmallAutoField(primary_key=True, serialize=False)),
                ('deviceType', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('SSD', 'SSD'), ('HDD', 'HDD'), ('PSU', 'PSU'), ('MOBO', 'MOTHERBOARD'), ('CASE', 'CASE'), ('COOLER', 'COOLER'), ('FAN', 'FAN')], max_length=12)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('power', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
