# Generated by Django 5.2 on 2025-04-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0004_alter_device_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sellerID',
            new_name='seller',
        ),
    ]
