# Generated by Django 5.2 on 2025-05-01 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0006_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='UserShipping',
        ),
    ]
