# Generated by Django 5.2 on 2025-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0007_rename_seller_usershipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-01T15:22:59Z'),
            preserve_default=False,
        ),
    ]
