# Generated by Django 5.2 on 2025-05-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedTiger', '0008_listing_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
